from  flask import Flask, jsonify 
import random 

app = Flask(__name__)

jokes = [
    {"id": 1, "content": "Why don't scientists trust atoms? Because they make up everything."},
    {"id": 2, "content": "Parallel lines have so much in common. It's a shame they'll never meet."},
    {"id": 3, "content": "I told my wife she was drawing her eyebrows too high. She looked surprised."},
    {"id": 4, "content": "Why did the scarecrow win an award? Because he was outstanding in his field!"},
    {"id": 5, "content": "I used to play piano by ear, but now I use my hands."},
    {"id": 6, "content": "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them."},
    {"id": 7, "content": "How do you organize a space party? You planet!"},
    {"id": 8, "content": "What's orange and sounds like a parrot? A carrot!"},
    {"id": 9, "content": "I'm reading a book on anti-gravity. It's impossible to put down!"},
    {"id": 10, "content": "Why don't skeletons fight each other? They don't have the guts."},
    {"id": 11, "content": "I told my wife she was drawing her eyebrows too high. She looked surprised."},
    {"id": 12, "content": "I used to be a baker, but I couldn't make enough dough."},
    {"id": 13, "content": "I'm reading a book on anti-gravity. It's impossible to put down!"},
    {"id": 14, "content": "What's orange and sounds like a parrot? A carrot!"},
    {"id": 15, "content": "Why don't skeletons fight each other? They don't have the guts."},
    {"id": 16, "content": "I'm on a seafood diet. I see food, and I eat it!"},
    {"id": 17, "content": "I told my computer I needed a break, and now it won't stop sending me Kit Kat bars."},
    {"id": 18, "content": "Why did the bicycle fall over? Because it was two-tired!"},
    {"id": 19, "content": "What do you call a bear with no teeth? A gummy bear!"},
    {"id": 20, "content": "Why was the math book sad? Because it had too many problems."},
    {"id": 21, "content": "I used to be a baker, but I couldn't make enough dough."},
    {"id": 22, "content": "I'm reading a book on anti-gravity. It's impossible to put down!"},
    {"id": 23, "content": "What's orange and sounds like a parrot? A carrot!"},
    {"id": 24, "content": "Why did Satan start a band? Because he had the best tunes in hell!"},
    {"id": 25, "content": "I'm on a seafood diet. I see food, and I eat it!"},
    {"id": 26, "content": "What's the difference between a book and a door? You can slam a door shut, but you can't slam a book shut."},
    {"id": 27, "content": "Why did the book cross the road? To get to the other side."},
    {"id": 28, "content": "What's the worst book you've ever read? The phone book. It's so boring, it put me to sleep."},
    {"id": 29, "content": "What do you call a fish with no eyes? Fsh!"},
    {"id": 30, "content": "What do you call a cow with no legs? Ground beef!"},
    {"id": 31, "content": "What do you call a deer with no eyes? No idear!"},
    {"id": 32, "content": "What do you call a beehive without any bees? A beehive!"},
    {"id": 33, "content": "What do you call a lazy kangaroo? A pouch potato!"},
    {"id": 34, "content": "What do you call a cow with a bell around her neck? A beefaroni!"},
    {"id": 35, "content": "What do you call a fish with no eyes and no mouth? Fsh!"},
    {"id": 36, "content": "What do you call a cow with a leg missing? Ground beef!"},
    {"id": 37, "content": "What do you call a deer with no eyes and no legs? Still no idear!"},
    {"id": 38, "content": "What do you call a beehive without any bees and no honey? A bee-utiful box!"},
    {"id": 39, "content": "What do you call a lazy kangaroo with a pouch full of babies? A pouch potato with fries!"},
    {"id": 40, "content": "What do you call a cow with a bell around her neck and a leg missing? Ground beefaroni!"},
    {"id": 41, "content": "What do you call a fish with no eyes, no mouth, and no fins? Sushi!"},
    {"id": 42, "content": "What do you call a cow with no eyes, no legs, and no mouth? Ground beefaroni sushi!"},
    {"id": 43, "content": "What do you call a deer with no eyes, no legs, and no mouth? Still no idear sushi!"},
    {"id": 44, "content": "What do you call a beehive without any bees, no honey, and no box? A bee-utiful bee-ing!"},
    {"id": 45, "content": "What do you call a lazy kangaroo with a pouch full of babies and no pouch? A pouch potato with no fries!"},
    {"id": 46, "content": "What do you call a cow with a bell around her neck, no leg, and no eyes? Ground beefaroni sushi with no idear!"},
    {"id": 47, "content": "What do you call a fish with no eyes, no mouth, no fins, and no head? Sushi soup!"},
    {"id": 48, "content": "What do you call a cow with no eyes, no legs, no mouth, and no head? Ground beefaroni sushi soup with no idear!"},
    {"id": 49, "content": "What do you call a deer with no eyes, no legs, no mouth, and no head? Still no idear sushi soup!"},
    {"id": 50, "content": "What do you call a beehive without any bees, no honey, no box, and no bee-ing? Nothing! It doesn't exist!"},
    {"id": 51, "content": "Why don't programmers like to go to the beach? Because they can't find the ocean for the data."},
    {"id": 52, "content": "How many programmers does it take to change a light bulb? None, that's a hardware issue."},
    {"id": 53, "content": "Why did the developer go broke? Because he lost all his cache."},
    {"id": 54, "content": "What's a programmer's favorite game? Hide and seek. They love to play it with bugs."},
    {"id": 55, "content": "Why did the computer catch a cold? Because it had a Windows open."},
    {"id": 56, "content": "Why do programmers always mix up work and play? Because they have 'Ctrl' issues!"},
    {"id": 57, "content": "Why don't programmers like to get lost? Because they can't stand to be out of their 'element.'"},
    {"id": 58, "content": "Why don't programmers like nature? It has too many bugs."},
    {"id": 59, "content": "Why do programmers always mix up their holidays? Because Oct 31 == Dec 25."},
    {"id": 60, "content": "Why don't programmers like coffee breaks? Because it's hard to ESPRESSO your thoughts in Java."},
    {"id": 61, "content": "What's a programmer's favorite hangout place? The Foo Bar."},
    {"id": 62, "content": "Why don't programmers like to make eye contact? Because they can't C#!"},
    {"id": 63, "content": "Why did the programmer go broke? Because he used up all his cache."},
    {"id": 64, "content": "What do you call a programmer from Finland? Nerdic."},
    {"id": 65, "content": "Why did the web developer stay calm? Because he had enough JavaScript to keep his cool."},
    {"id": 66, "content": "How do programmers stay cool in the summer? They use fans."},
    {"id": 67, "content": "Why did the programmer quit his job? Because he didn't get arrays."},
    {"id": 68, "content": "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25."},
    {"id": 69, "content": "What did the computer do at lunchtime? It had a byte."},
    {"id": 70, "content": "Why did the programmer go broke? Because he used up all his cache."},
    {"id": 71, "content": "What's a programmer's favorite place in New York? The Big Apple."},
    {"id": 72, "content": "Why do programmers prefer iOS development over Android development? Because on iOS, they don't have to deal with Java."},
    {"id": 73, "content": "Why do programmers always mix up work and pleasure? Because they get lost in the 'cloud.'"},
    {"id": 74, "content": "Why do programmers never break up with their computers? Because they don't want to lose their data."},
    {"id": 75, "content": "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25."},
    {"id": 76, "content": "Why did the programmer go broke? Because he used up all his cache."},
    {"id": 77, "content": "Why do programmers always mix up work and pleasure? Because they get lost in the 'cloud.'"},
    {"id": 78, "content": "Why do programmers never break up with their computers? Because they don't want to lose their data."},
    {"id": 79, "content": "Why do programmers prefer iOS development over Android development? Because on iOS, they don't have to deal with Java."},
    {"id": 80, "content": "Why did the web developer stay calm? Because he had enough JavaScript to keep his cool."},
    {"id": 81, "content": "How do programmers stay cool in the summer? They use fans."},
    {"id": 82, "content": "Why did the programmer quit his job? Because he didn't get arrays."},
    {"id": 83, "content": "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25."},
    {"id": 84, "content": "What did the computer do at lunchtime? It had a byte."},
    {"id": 85, "content": "Why did the programmer go broke? Because he used up all his cache."},
    {"id": 86, "content": "What's a programmer's favorite place in New York? The Big Apple."},
    {"id": 87, "content": "Why do programmers prefer iOS development over Android development? Because on iOS, they don't have to deal with Java."},
    {"id": 88, "content": "Why do programmers always mix up work and pleasure? Because they get lost in the 'cloud.'"},
    {"id": 89, "content": "Why do programmers never break up with their computers? Because they don't want to lose their data."},
    {"id": 90, "content": "Why do programmers prefer iOS development over Android development? Because on iOS, they don't have to deal with Java."},
    {"id": 91, "content": "Why did the web developer stay calm? Because he had enough JavaScript to keep his cool."},
    {"id": 92, "content": "How do programmers stay cool in the summer? They use fans."},
    {"id": 93, "content": "Why did the programmer quit his job? Because he didn't get arrays."},
    {"id": 94, "content": "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25."},
    {"id": 95, "content": "What did the computer do at lunchtime? It had a byte."},
    {"id": 96, "content": "Why did the programmer go broke? Because he used up all his cache."},
    {"id": 97, "content": "What's a programmer's favorite place in New York? The Big Apple."},
    {"id": 98, "content": "Why do programmers prefer iOS development over Android development? Because on iOS, they don't have to deal with Java."},
    {"id": 99, "content": "Why do programmers always mix up work and pleasure? Because they get lost in the 'cloud.'"},
    {"id": 100, "content": "Why do programmers never break up with their computers? Because they don't want to lose their data."}
    ]

@app.route("/api/jokes", methods= ['GET'])
def get_random_jokes():
    random_jokes = random.choice(jokes)
    return jsonify(random_jokes)

if __name__ == "__main__":
    app.run()